/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.18
 * Generated at: 2026-04-29 06:19:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import ma.ac.esi.culinaryarts.model.Recipe;

public final class recipes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("ma.ac.esi.culinaryarts.model.Recipe");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"fr\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Catalogue Gastronomique - Culinary Arts</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("            background-color: #f4f7f6;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("        }\r\n");
      out.write("        h1 {\r\n");
      out.write("            color: #2c3e50;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            letter-spacing: 2px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Grille de cartes */\r\n");
      out.write("        .recipes-grid {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("            gap: 25px;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Style de la carte */\r\n");
      out.write("        .recipe-card {\r\n");
      out.write("            background: white;\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            width: 300px;\r\n");
      out.write("            box-shadow: 0 10px 20px rgba(0,0,0,0.05);\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            transition: transform 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .recipe-card:hover {\r\n");
      out.write("            transform: translateY(-10px);\r\n");
      out.write("            box-shadow: 0 15px 30px rgba(0,0,0,0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Zone Image */\r\n");
      out.write("        .recipe-image {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 200px;\r\n");
      out.write("            background-color: #ddd;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .recipe-image img {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            object-fit: cover;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Contenu de la carte */\r\n");
      out.write("        .recipe-content {\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            flex-grow: 1;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .recipe-title {\r\n");
      out.write("            font-size: 1.25rem;\r\n");
      out.write("            color: #e91e63;\r\n");
      out.write("            margin: 0 0 10px 0;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .recipe-category {\r\n");
      out.write("            font-size: 0.85rem;\r\n");
      out.write("            color: #7f8c8d;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .recipe-description {\r\n");
      out.write("            font-size: 0.95rem;\r\n");
      out.write("            color: #34495e;\r\n");
      out.write("            line-height: 1.5;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("            flex-grow: 1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .recipe-footer {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            border-top: 1px solid #eee;\r\n");
      out.write("            padding-top: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .chef-name {\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("            color: #2c3e50;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .price {\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: #27ae60;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .no-data {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            color: #95a5a6;\r\n");
      out.write("            margin-top: 50px;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-add {\r\n");
      out.write("    background-color: #e91e63; /* Rose signature */\r\n");
      out.write("    color: white;\r\n");
      out.write("    padding: 12px 25px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    border-radius: 30px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    transition: all 0.3s ease;\r\n");
      out.write("    box-shadow: 0 4px 15px rgba(233, 30, 99, 0.3);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-add:hover {\r\n");
      out.write("    background-color: #c2185b;\r\n");
      out.write("    transform: translateY(-2px);\r\n");
      out.write("    box-shadow: 0 6px 20px rgba(233, 30, 99, 0.4);\r\n");
      out.write("}\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <h1>Marketplace Culinary Arts</h1>\r\n");
      out.write("    <div class=\"header-actions\" style=\"display: flex; justify-content: space-between; align-items: center; margin-bottom: 30px;\">\r\n");
      out.write("    <h1>Catalogue Gastronomique</h1>\r\n");
      out.write("    \r\n");
      out.write("    <a href=\"");
      out.print( request.getContextPath() );
      out.write("/RecipeSubmitController\" class=\"btn-add\">\r\n");
      out.write("        + Ajouter une Recette\r\n");
      out.write("    </a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("    ");
 
        String category = (String) request.getAttribute("currentCategory");
        if (category != null && !category.isEmpty()) {
    
      out.write("\r\n");
      out.write("        <p style=\"text-align:center; color: #666; margin-bottom: 30px;\">\r\n");
      out.write("            Filtre actif : <strong>");
      out.print( category );
      out.write("</strong>\r\n");
      out.write("        </p>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("    <div class=\"user-info\">\r\n");
      out.write("    <span>\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        👤 ");
      out.print( session.getAttribute("user") != null 
              ? session.getAttribute("user") : "Visiteur" );
      out.write("\r\n");
      out.write("    </span>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
 if (session.getAttribute("user") != null) { 
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <form action=\"");
      out.print( request.getContextPath() );
      out.write("/LogoutController\" method=\"post\"> \r\n");
      out.write("        <button type=\"submit\" class=\"logout-btn\">\r\n");
      out.write("            Déconnexion\r\n");
      out.write("        </button>\r\n");
      out.write("    </form>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"recipes-grid\">\r\n");
      out.write("        ");
 
            List<Recipe> recipes = (List<Recipe>) request.getAttribute("recipesAttr");
            
            if (recipes != null && !recipes.isEmpty()) {
                for (Recipe r : recipes) {
        
      out.write("\r\n");
      out.write("            <div class=\"recipe-card\">\r\n");
      out.write("                <div class=\"recipe-image\">\r\n");
      out.write("                    <img src=\"assets/images/");
      out.print( r.getImageUrl() );
      out.write("\" alt=\"");
      out.print( r.getTitle() );
      out.write("\">\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"recipe-content\">\r\n");
      out.write("                    <span class=\"recipe-category\">");
      out.print( r.getCategory() );
      out.write("</span>\r\n");
      out.write("                    <h3 class=\"recipe-title\">");
      out.print( r.getTitle() );
      out.write("</h3>\r\n");
      out.write("                    <p class=\"recipe-description\">");
      out.print( r.getDescription() );
      out.write("</p>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"recipe-footer\">\r\n");
      out.write("                        <span class=\"chef-name\">👨‍🍳 ");
      out.print( r.getChefName() );
      out.write("</span>\r\n");
      out.write("                        <span class=\"price\">");
      out.print( r.getPrice() );
      out.write(" €</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 
                }
            } else {
        
      out.write("\r\n");
      out.write("            <div class=\"no-data\">\r\n");
      out.write("                <h3>Aucune recette disponible.</h3>\r\n");
      out.write("                <p>Revenez plus tard pour découvrir les nouvelles créations de nos chefs.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
