/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.18
 * Generated at: 2026-04-29 11:47:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import ma.ac.esi.culinaryarts.model.Recipe;

public final class editRecipe_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("ma.ac.esi.culinaryarts.model.Recipe");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    Recipe recipe = (Recipe) request.getAttribute("recipe");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"fr\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Modifier la Recette</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        /* Même style que submitRecipe.jsp */\r\n");
      out.write("        body { font-family: 'Segoe UI', sans-serif; background: #f4f7f6; margin: 0; padding: 20px; }\r\n");
      out.write("        .form-container { max-width: 600px; margin: auto; background: white;\r\n");
      out.write("                          padding: 40px; border-radius: 15px;\r\n");
      out.write("                          box-shadow: 0 10px 20px rgba(0,0,0,0.08); }\r\n");
      out.write("        h2 { color: #e91e63; text-align: center; margin-bottom: 30px; }\r\n");
      out.write("        .form-group { margin-bottom: 20px; }\r\n");
      out.write("        label { display: block; margin-bottom: 6px; font-weight: bold; color: #2c3e50; }\r\n");
      out.write("        input, select, textarea {\r\n");
      out.write("            width: 100%; padding: 10px 14px; border: 1px solid #ddd;\r\n");
      out.write("            border-radius: 8px; box-sizing: border-box; font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("        textarea { resize: vertical; min-height: 100px; }\r\n");
      out.write("        .btn-save {\r\n");
      out.write("            width: 100%; padding: 12px; background-color: #3498db;\r\n");
      out.write("            color: white; border: none; border-radius: 25px;\r\n");
      out.write("            font-size: 16px; font-weight: bold; cursor: pointer;\r\n");
      out.write("            transition: background 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-save:hover { background-color: #2980b9; }\r\n");
      out.write("        .btn-cancel {\r\n");
      out.write("            display: block; text-align: center; margin-top: 15px;\r\n");
      out.write("            color: #7f8c8d; text-decoration: none; font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("        .message { padding: 10px; border-radius: 8px; margin-bottom: 20px; text-align: center; }\r\n");
      out.write("        .success { background: #d5f5e3; color: #1e8449; }\r\n");
      out.write("        .error   { background: #fadbd8; color: #922b21; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"form-container\">\r\n");
      out.write("    <h2>✏️ Modifier la Recette</h2>\r\n");
      out.write("\r\n");
      out.write("    ");
 if (request.getAttribute("message") != null) { 
      out.write("\r\n");
      out.write("        <div class=\"message success\">");
      out.print( request.getAttribute("message") );
      out.write("</div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("    ");
 if (request.getAttribute("error") != null) { 
      out.write("\r\n");
      out.write("        <div class=\"message error\">");
      out.print( request.getAttribute("error") );
      out.write("</div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <form action=\"");
      out.print( request.getContextPath() );
      out.write("/RecipeEditController\" method=\"post\">\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        <input type=\"hidden\" name=\"id\" value=\"");
      out.print( recipe.getId() );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label>Titre</label>\r\n");
      out.write("            <input type=\"text\" name=\"title\" value=\"");
      out.print( recipe.getTitle() );
      out.write("\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label>Catégorie</label>\r\n");
      out.write("            <select name=\"category\">\r\n");
      out.write("                <option ");
      out.print( "Entrée".equals(recipe.getCategory())  ? "selected" : "" );
      out.write(">Entrée</option>\r\n");
      out.write("                <option ");
      out.print( "Plat".equals(recipe.getCategory())    ? "selected" : "" );
      out.write(">Plat</option>\r\n");
      out.write("                <option ");
      out.print( "Dessert".equals(recipe.getCategory()) ? "selected" : "" );
      out.write(">Dessert</option>\r\n");
      out.write("                <option ");
      out.print( "Boisson".equals(recipe.getCategory()) ? "selected" : "" );
      out.write(">Boisson</option>\r\n");
      out.write("            </select>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label>Nom du Chef</label>\r\n");
      out.write("            <input type=\"text\" name=\"chefName\" value=\"");
      out.print( recipe.getChefName() );
      out.write("\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label>Description</label>\r\n");
      out.write("            <textarea name=\"description\">");
      out.print( recipe.getDescription() );
      out.write("</textarea>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label>Prix (€)</label>\r\n");
      out.write("            <input type=\"number\" name=\"price\" step=\"0.01\" \r\n");
      out.write("                   value=\"");
      out.print( recipe.getPrice() );
      out.write("\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <button type=\"submit\" class=\"btn-save\">💾 Enregistrer les modifications</button>\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/recipes\" class=\"btn-cancel\">← Annuler</a>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
