/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.18
 * Generated at: 2026-04-29 09:54:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class submitRecipe_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"fr\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Ajouter une Recette — Culinary Arts</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body { font-family: 'Segoe UI', sans-serif; background-color: #f4f7f6; color: #2c3e50; padding: 40px 20px; }\r\n");
      out.write("        .container { max-width: 700px; margin: auto; background: white; padding: 40px; border-radius: 20px; box-shadow: 0 15px 35px rgba(0,0,0,0.05); }\r\n");
      out.write("        h1 { color: #e91e63; text-align: center; margin-bottom: 30px; }\r\n");
      out.write("        .form-row { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }\r\n");
      out.write("        .form-group { margin-bottom: 20px; }\r\n");
      out.write("        label { display: block; margin-bottom: 8px; font-weight: 600; }\r\n");
      out.write("        input, select, textarea { width: 100%; padding: 12px; border: 1px solid #ddd; border-radius: 10px; box-sizing: border-box; }\r\n");
      out.write("        button { width: 100%; padding: 15px; background: #27ae60; color: white; border: none; border-radius: 12px; cursor: pointer; font-size: 1.1rem; font-weight: bold; transition: 0.3s; }\r\n");
      out.write("        button:hover { background: #219150; }\r\n");
      out.write("        .success { background: #d4edda; color: #155724; padding: 15px; border-radius: 10px; margin-bottom: 20px; }\r\n");
      out.write("        .error { background: #f8d7da; color: #721c24; padding: 15px; border-radius: 10px; margin-bottom: 20px; }\r\n");
      out.write("        .file-input { background: #fafafa; border: 2px dashed #ddd; padding: 20px; text-align: center; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <h1>Partagez votre Création</h1>\r\n");
      out.write(" \r\n");
      out.write("    ");
 String message = (String) request.getAttribute("message"); 
      out.write("\r\n");
      out.write("    ");
 String error = (String) request.getAttribute("error"); 
      out.write("\r\n");
      out.write("    ");
 if (message != null) { 
      out.write("<div class=\"success\">✅ ");
      out.print( message );
      out.write("</div>");
 } 
      out.write("\r\n");
      out.write("    ");
 if (error != null) { 
      out.write("<div class=\"error\">❌ ");
      out.print( error );
      out.write("</div>");
 } 
      out.write("\r\n");
      out.write(" \r\n");
      out.write("    <form action=\"");
      out.print( request.getContextPath() );
      out.write("/RecipeSubmitController\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"form-group file-input\">\r\n");
      out.write("            <label for=\"imageFile\">Photo du plat *</label>\r\n");
      out.write("            <input type=\"file\" id=\"imageFile\" name=\"imageFile\" accept=\"image/*\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"title\">Nom de la recette *</label>\r\n");
      out.write("            <input type=\"text\" id=\"title\" name=\"title\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-row\">\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"category\">Catégorie</label>\r\n");
      out.write("                <select id=\"category\" name=\"category\">\r\n");
      out.write("                    <option value=\"Entrée\">Entrée</option>\r\n");
      out.write("                    <option value=\"Plat\">Plat Principal</option>\r\n");
      out.write("                    <option value=\"Dessert\">Dessert</option>\r\n");
      out.write("                    <option value=\"Boisson\">Boisson</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"price\">Prix (€)</label>\r\n");
      out.write("                <input type=\"number\" id=\"price\" name=\"price\" step=\"0.01\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"chefName\">Nom du Chef</label>\r\n");
      out.write("            <input type=\"text\" id=\"chefName\" name=\"chefName\">\r\n");
      out.write("        </div>\r\n");
      out.write(" \r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"description\">Description</label>\r\n");
      out.write("            <textarea id=\"description\" name=\"description\"></textarea>\r\n");
      out.write("        </div>\r\n");
      out.write(" \r\n");
      out.write("        <button type=\"submit\">Publier la recette</button>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
